#!/bin/bash
set -e
# Automatic Nodejs isolation script using docker (or rootless docker)

# this is the bin that we are trying to run from link
BINPATH="$(dirname "$(realpath "$0")")"
RUNBIN="$(basename $0)"
# this is the main script name
MAINSCRIPT="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

# default access (ro)
RUNACCESS="ro"

##########################
### RUNTIME CODE BELOW ###
##########################

accesspatt="(.*)-(rw)$"

#echo $RUNBIN $RUNACCESS
if [[ $RUNBIN =~ $accesspatt ]]; then
	RUNBIN="${BASH_REMATCH[1]}"
        RUNACCESS="${BASH_REMATCH[2]}"
fi
#echo $RUNBIN $RUNACCESS

for BINNAME in node nodejs npm npx  node-rw nodejs-rw npm-rw npx-rw; do
	[ -f "$BINPATH/$BINNAME" ] || ln -s "$BINPATH/$MAINSCRIPT" "$BINPATH/$BINNAME"
done


if [[ $RUNBIN == "$MAINSCRIPT" ]]; then
        echo "$MAINSCRIPT: install done"
        exit
fi

if [ ! -x "`command -v docker`" ]; then
  echo "$MAINSCRIPT: docker not installed.... now installing as rootless..."

  sudo apt-get update

  bash <(curl -s https://get.docker.com)

  # https://docs.docker.com/engine/security/rootless/
  sudo apt-get install -y uidmap
  sudo apt-get install -y dbus-user-session
  
  # fuse-overlayfs is a requiremnt per limitations: https://docs.docker.com/engine/security/rootless/
  sudo apt-get install -y fuse-overlayfs

  dockerd-rootless-setuptool.sh install
  sudo systemctl disable --now docker.service docker.socket
  
  sudo setcap cap_net_bind_service=ep /usr/bin/rootlesskit
  echo net.ipv4.ip_unprivileged_port_start=0 | sudo tee --append "/etc/sysctl.conf"
  sudo sysctl --system
fi

# runs nodejs (LTS version)
docker run -it --rm --name my-running-script -v "$PWD:/usr/src/app:$RUNACCESS" -w /usr/src/app node:16 "$RUNBIN" "$@"
